"""empty message

Revision ID: 058be7f4bd85
Revises: 593522ef0604
Create Date: 2024-06-26 19:15:26.487962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058be7f4bd85'
down_revision = '593522ef0604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_talent', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('seeking_description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('seeking_talent')

    # ### end Alembic commands ###
