"""empty message

Revision ID: 985670fb843a
Revises: 058be7f4bd85
Create Date: 2024-06-28 14:15:31.181321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985670fb843a'
down_revision = '058be7f4bd85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_venue', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('seeking_description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('seeking_venue')

    # ### end Alembic commands ###
